GET http://localhost:5000/customers

###
GET http://localhost:5000/rooms

###
GET http://localhost:5000/rooms/636675c16dea9e30e55a9657

###
GET http://localhost:5000/customers

###
PATCH  http://localhost:5000/rooms/636715d9904b4f873c245c12

###
GET http://localhost:5000/bookings

###
POST http://localhost:5000/bookings {
    "customer_id": "63632c1a8d3254611e93eda9",
    "room_id": "636675c16dea9e30e55a9657",
    "check_in": "2019-01-01",
    "check_out": "2019-01-02"
    "total" : 100
}

###
POST http://localhost:5000/rooms
Content-Type: application/json

{
    "name": "testing",
    "price": 100,
    "bed": "2",
    "facility": "TV, AC",
    "status": "available"
}

###
POST http://localhost:5000/customers
Content-Type: application/json

{
    "name": "Test",
    "address": "Test",
    "phone": "Test"
}

###
POST http://localhost:5000/bookings
Content-Type: application/json

{
    "id_room": "636bd569d4ca3c93b3e47324",
    "id_customer": "636bd4d8c21d3a50883a1b6f",
    "check_in": "2019-01-01",
    "check_out": "2019-01-02",
    "total" : 100
}